name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  packages: read

jobs:
  main:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') }}
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Build Primitives
        run: pnpm primitives:build

      - name: Build Components
        run: pnpm components:build

      - name: Build shadcn
        run: pnpm shadcn:build

      - name: Build taxonomy
        run: pnpm showcase-taxonomy:build

      - name: Build dashboard
        run: pnpm showcase-dashboard:build

      - name: Test Primitives
        run: pnpm primitives:test

      - name: Linters
        run: |
          pnpm run prettier
          pnpm run stylelint --max-warnings=0
          pnpm run eslint --max-warnings=0
