name: PR Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Check PR title with commitlint
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
